project:
  type: book

book:
  title: "Conferencias de Miguel Anxo Bastos, Volumen I"
  author:
  - name: "Coditia"
    email: "info@coditia.com"
  date: today
  language: es
  chapters:
    - index.qmd
    - 01-capitalismo-vs-socialismo.qmd
    - 02-la-revolucion-francesa.qmd
    - 03-el-fracaso-de-la-agenda-2030.qmd
    - references.qmd
  site-url: https://www.miguelanxobastos.org/conferencias_vol_i/
  description: "Conferencias de Miguel Anxo Bastos, Volumen I."
  sharing: []

bibliography: book.bib
csl: chicago-fullnote-bibliography.csl

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    respect-user-color-scheme: true
    include-in-header: extra_headers.html
    toc: true
    number-sections: false
    lang: es
    grid:
      sidebar-width: 250px
      body-width: 900px
